# Generated by Django 5.0.1 on 2024-01-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_book_options_book_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='participants',
            new_name='members',
        ),
    ]
